# Secrets for Streamlit Community Cloud
# Add these in your Streamlit Cloud dashboard under "Secrets"

[general]
email = "your-email@example.com"

[openai]
api_key = "your-openai-api-key-here"

[simulation]
default_mission_duration = 3600
default_time_step = 1.0

[rag]
chroma_db_path = "./data/chroma_db"
collection_name = "space_missions"
